services:
  backend:
    build: .
    container_name: stocksync-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "python", "-m", "flask", "--app", "app", "run", "--host=0.0.0.0", "--port=5000"]

  db:
    image: mysql:8.0
    container_name: stocksync-db
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./uploads:/app/uploads

volumes:
  mysql_data:
